### ISSUE TITLE
"Disconnected from the server"

### ISSUE THREAD

**Issue by Ederson7** [msperlin/GetDFPData#14]
Olá.
Tenho tentado fazer o download dos balanços de algumas empresas via "https://www.msperlin.com/shiny/GetDFPData/" mas pouquíssimas vezes não sou desconectado do servidor. Tentei com xlsx, csv e rds, alternando entre DFP, FRE e FCA.
Utilizando o código gerado de uma das vezes que deu certo, no R, acontece o seguinte erro:
"Processing 4170 - VALE S.A.
        Finding info from Bovespa
                Found BOV cache file
        Processing 4170 - VALE S.A. | date 2017-12-31
                Acessing DFP data | downloading fileError in utils::download.file(url = dl.link, destfile = dest.file, method = "wget",  : 
  'wget' call had nonzero exit status
Além disso: Warning message:
execução do comando 'wget --no-check-certificate --quiet "http://www.rad.cvm.gov.br/enetconsulta/frmDownloadDocumento.aspx?CodigoInstituicao=2&NumeroSequencialDocumento=71834" -O "C:\Users\Ederson\AppData\Local\Temp\RtmpcRipYZ/DFP_VALE_4170_2017-12-31_idfile_71834_verfile_1.zip"' teve status 127 
Error in if (file.size(dest.file) < 10) { : 
  valor ausente onde TRUE/FALSE necessário "
Estou fazendo algo errado?
![erro_getdfpdata_web](https://user-images.githubusercontent.com/47058443/51788073-f905e180-2160-11e9-8c1c-fdfb714bb095.jpg)

**Comment by Ederson7** [comment]
Esqueci de dizer que estou usando:
Windows 7
Firefox 64.0.2
R 3.4.4

**Comment by msperlin** [comment]
Oi Ederson,

Acabei de testar em https://www.msperlin.com/shiny/GetDFPData/ e funcionou sem problema. 

Também testei a versão do R e funcionou:

Processing 4170 - VALE S.A.
	Finding info from Bovespa | downloading and reading data | saving cache
	Processing 4170 - VALE S.A. | date 2017-12-31
		Acessing DFP data | downloading file | reading file | saving cache
		Acessing FRE data | downloading file | reading file | saving cache
		Acessing FCA data | downloading file | reading file | saving cache

Chegaste a atualizar para a versão 1.4? Ou talvez o site da B3 estava fora do ar. Tente de novo e me diga como foi.

**Comment by Ederson7** [comment]
Realmente ocorre o mesmo erro. Atualizei a versão do R para 3.5.2 e executei "install.packages("GetDFPData")", mas ainda assim não funcionou.

**Comment by msperlin** [comment]
Testei novamente e aqui continua funcionando. Não sei o que lhe dizer.

**Comment by msperlin** [comment]
Talvez um firewall esteja bloqueando. Tente por outra conexão de internet.

**Comment by Ederson7** [comment]
Tentei em casa com conexão wi-fi e não funcionou. No trabalho também não. Mas obrigado pela ajuda assim mesmo. 










Ederson S. Martins








 

    Em quinta-feira, 31 de janeiro de 2019 15:10:17 BRST, Marcelo S. Perlin <notifications@github.com> escreveu:  
 
 
Talvez um firewall esteja bloqueando. Tente por outra conexão de internet.
