### ISSUE TITLE
Can't work function - gdfpd.GetDFPData

### ISSUE THREAD

**Issue by Lvitor** [msperlin/GetDFPData#15]
> df.reports <- gdfpd.GetDFPData(name.companies = name.companies, first.date = first.Tdate,last.date = last.date,cache.folder = tempdir())

Processing 9512 - PETRÓLEO BRASILEIRO  S.A.  - PETROBRAS
	Finding info from Bovespa | downloading and reading data | saving cache
	Processing 9512 - PETRÓLEO BRASILEIRO  S.A.  - PETROBRAS | date 2005-12-31
		Acessing DFP data | downloading file | reading file**Error in if (file.size(my.f) == 0) { : 
  missing value where TRUE/FALSE needed**

Thank you!

**Comment by msperlin** [comment]
There was a bug. Its now fixed in github. Just reinstall using devtools::install_github().

I'm posting the new version to CRAN right now.

**Comment by Lvitor** [comment]
Thank you so much!!



Enviado do meu iPhone

Em 14 de fev de 2019, à(s) 10:39, Marcelo S. Perlin <notifications@github.com> escreveu:
