### ISSUE TITLE
Atualização das empresas com resultado de 2018.

### ISSUE THREAD

**Issue by Lvitor** [msperlin/GetDFPData#17]
Msperlin, tudo bem? 

Eu fiz uma atualização do seu arquivo InfoBovespa, com os dados mais recentes das empreas que tiveram negociação em 2019 (219 empresas). Eu fiz uma codigo (ainda não esta em forma de função, mas posso te encaminhar) usando o RSelenium para fazer um webscraping  no endereço http://siteempresas.bovespa.com.br/consbov/ExibeTodosDocumentosCVM.asp?CNPJ=61.024.352/0001-71&CCVM= 
Ele já devolve o id.file tanto para DPF, como para ITR, Relatorio Referencial etcs.

Abraços.

[InfoBovespaCompanies.zip](https://github.com/msperlin/GetDFPData/files/2898482/InfoBovespaCompanies.zip)

**Comment by msperlin** [comment]
Oi Vitor,

Eu devo atualizar os dados assim que todas entregarem o DFP. Podes também utilizar a opção para atualizar os arquivos pelo input fetch.new.files (ou algo assim).

Obrigado pelo trabalho. Vou dar uma olhada no que fizes assim que puder. 

Abc.
