### ISSUE TITLE
Arquivos xlsx

### ISSUE THREAD

**Issue by rrsjunior23** [msperlin/GetDFPData#18]
Boa noite, tudo bom?

Primeiramente gostaria de parabenizar pelo trabalho, venho a um bom tempo procurando um canal com as informações financeiras da empresas de uma maneira sistemática, confiável e organizada. De longe get DFP foi a melhor plataforma que achei e construí toda minha base de análises  e valuation com inputs dela. 
Acontece que não tenho domínio em RDS e CSV, e acabei usando o formato de excel mesmo, e, de um tempo para cá não tenho conseguido exportar os dados nesse formato.
Gostaria de saber se isso foi um problema pontual ou se o site deve voltar a ter a opção de output xlsx pois caso contrário vou ter que descobrir como fazer adaptações.

Desde já agradeço,

Ronaldo

**Comment by msperlin** [comment]
Oi Ronaldo,

Tive que atualizar a versão do R no servidor e isso acabou dando um problema no GetDFPDAta-shiny: falta memória para salvar os arquivos em xlsx. Por isso que ocultei a opção na interface. 

Devo investigar esse problema assim q tiver um tempo. Infelizmente não consigo confirmar ou não se irei resolver.

Minha sugestão é utilizar a versão R do pacote. Nela podes importar os dados e salvar em qualquer formato.

Abc.
