### ISSUE TITLE
Problem in dividends

### ISSUE THREAD

**Issue by msperlin** [msperlin/GetDFPData#20]
Divergence between dividends in FRE/DFP and from datasets. 

DFP:
![image001](https://user-images.githubusercontent.com/10583352/54534946-39692b00-496c-11e9-9784-a64db6cf3707.jpg)

From code:
PETRÓLEO BRASILEIRO S.A. - PETROBRAS | 2016-12-31 | 6.03.05 | Dividendos Pagos a Acionistas | -8735000
-- | -- | -- | -- | --

**Comment by msperlin** [comment]
Checked values in df.cashflow and it matched. There is no bug. 

The difference from the picture is due to looking at "consolidated" instead of "individual" financial reports.

**Comment by gpinheirodaniel** [comment]
I still don't get it. Sorry, bother you again.

Tried excel spreadsheet download from getdfp web interface (both consolidated and individual) and doesn't match with dataset consolidated or individual. The same result when I manipulate in my RStudio.

$history.dividends match dataset, but $fr.cashflow.consolidated and $fr.cashflow i can't get the same result.

![imagem1](https://user-images.githubusercontent.com/38118487/55034132-88a9fe00-4ff3-11e9-80b2-b999b9bd5f55.JPG)
![imagem2](https://user-images.githubusercontent.com/38118487/55034133-88a9fe00-4ff3-11e9-833e-f0c58191a671.JPG)
![imagem3](https://user-images.githubusercontent.com/38118487/55034134-89429480-4ff3-11e9-888c-7e885994033f.jpg)
![imagem4](https://user-images.githubusercontent.com/38118487/55034135-89429480-4ff3-11e9-8ffb-866cc734e71c.JPG)

**Comment by msperlin** [comment]
This might be a bug related to the other issue, duplicate entries. The web version data is not reliable as the company may have updated the files or the data was compromised (I'll update it soon).

Try the following, erase ALL of your cache files ("DFP cache folder"), import data for PETROBRAS and compare it again. 

I"ve done that here, in Linux, and it worked fine. See below:

![Individual](https://user-images.githubusercontent.com/10583352/55035333-6ebdea80-4ff6-11e9-8da9-52368158dd70.png)

![Consolidated](https://user-images.githubusercontent.com/10583352/55035363-8bf2b900-4ff6-11e9-8797-d2ed2a4638b7.png)

Let me know how it goes.

**Comment by gpinheirodaniel** [comment]
I think i erase all the cache files once. But I will try it again.

I just saw in your picture 6.03.05 account from 2017, it is ok here. 
I can't see 6.03.05 account from 2016 and 2015, where i have the problems.

When I look only 6.03 it matchs, but 6.03.05 don't. 

Thx

**Comment by msperlin** [comment]
I checked and was able to replicate the problem for 6.03.05/2016/PETR. I'll have a deeper look soon, give me a couple of days.

**Comment by msperlin** [comment]
I just fixed the issue. The new code is already in github.
