### ISSUE TITLE
Notas Explicativas e Relatorio da Adminsitraçao

### ISSUE THREAD

**Issue by mmcodesso** [msperlin/GetDFPData#23]
Bom dia amigo,

Muito legal o trabalho.

Eu precisava baixar tambem as notas explicativas e o relatorio da administração. É posivel baixar tambem? 
Estou disposto a contribuir no desenvolvimento tambem.

Abraços.

**Comment by msperlin** [comment]
Obrigado mm.

Acredito que sim. O problema é que os dados não estão estruturados na NE e relatório e, por isso, perde a finalidade frente ao objetivo do pacote. 

Caso quiser colaborar, a maneira mais fácil é construir uma função que busque esses arquivos na b3.  Envie essa função via pull request que avalio.

Abc.
