### ISSUE TITLE
Problem to download data with file FRE

### ISSUE THREAD

**Issue by i-am-roger** [msperlin/GetDFPData#24]
Windows 10
R Version: 3.6.0

I’m trying to download data from different companies using code below: 

![Code](https://user-images.githubusercontent.com/54459778/63637268-27915f80-c651-11e9-873b-73777b1a5fb3.jpg)

But for some companies, I’m getting this message of error: 

![Error](https://user-images.githubusercontent.com/54459778/63637313-a5ee0180-c651-11e9-9e99-2e63556dcc8a.jpg)

However, if I take off FRE file the code work well. 

Some companies with error:
- Tecnisa S/A
- Trisul S/A
- MRE Engenharia e Participações

Some companies working well:
- Metalurgica Gerdau SA
- Grendente SA
- Qualicorp SA

**Comment by msperlin** [comment]
The problem is that your cache is from an older version. Try cleaning up the cache (delete all files from "GetDFPData Cache" folder) and run it again. Unfortunately, there is no other way around it.

Let me know how it goes. If you get the same issue, post your code and I'll have a look.
