### ISSUE TITLE
Erro de redirecionamento ao clicar no link do Shiny

### ISSUE THREAD

**Issue by wrprates** [msperlin/GetDFPData#26]
Ao clicar no link do Shiny < https://www.msperlin.com/shiny/GetDFPData/ > há algum redirecionamento  que tira o "shiny/" do link e abre uma página de erro 404. Aí é preciso acrescentar manualmente o "shiny/" de volta na URL. Acredito ser algum erro causado pelo nginx e não do shiny em sim. Segue print que mostra que, ao clicar no link correto em um compartilhamento pelo whatsapp, o link abre errado no navegador e dá erro 404.

![image](https://user-images.githubusercontent.com/10858085/65072418-3ffe4c80-d967-11e9-906e-0087f2565fa9.png)

Valeu!! Parabéns pelo projeto todo!!! É excelente!

**Comment by msperlin** [comment]
Oi Wr, 

Engraçado, nunca tinha visto esse problema. Obrigado por me avisar. 
Vou tentar replicar aqui.

Abraço.
