### ISSUE TITLE
GetDFPData problem

### ISSUE THREAD

**Issue by ghost** [msperlin/GetDFPData#28]
Hello Marcelo,

Tried using the function below
```R



official_name = gdfpd.search.company('PETRÓLEO BRASILEIRO  S.A.')[1]

gdfpd.GetDFPData(official_name)
```

And got this error:

```R

> sh: wget: command not found
Error in utils::download.file(url = dl.link, destfile = dest.file, method = "wget",  : 
  'wget' call had nonzero exit status
In addition: Warning message:
In system(paste("wget", paste(extra, collapse = " "), shQuote(url),  :
  error in running command
Error in if (file.size(dest.file) < 10) { : 
  missing value where TRUE/FALSE needed
```

**Comment by msperlin** [comment]
Hi Tomas,

You're missing wget. Just install it in your linux machine and it should work fine.

**Comment by ClarissaCapaverde** [comment]
Olá, estou com o mesmo erro. Através do Terminal instalei o Wget usando o Brew. Ao finalizar a instalação do Wget aparece a seguinte mensagem no terminal: wget: missing URL Usage: wget [OPTION]... [URL]... Try `wget --help' for more options.

Entro no R e rodo o comando:

 library(GetFREData)

# set options
id_companies <- 23264
first_year <- 2017
last_year  <- 2018

# download data
l_fre <- get_fre_data(companies_cvm_codes = id_companies,
                      first_year = first_year,
                      last_year = last_year)

Porém aparece o seguinte erro:

Fetching ftp contents
	* Reading fre_cia_aberta_2017.zip
sh: wget: command not found
Error in utils::download.file(url = dl_link, destfile = dest_file, method = "wget",  : 
  'wget' call had nonzero exit status
In addition: Warning message:
In system(paste("wget", paste(extra, collapse = " "), shQuote(url),  :
  error in running command
Error in if (file.size(dest_file) < 10) { : 
  missing value where TRUE/FALSE needed

Como posso resolver? Meu computador é um Mac.

**Comment by msperlin** [comment]
Oi clarissa, 

Pode ter sido um problema no link, do lado da B3. Ontem o site estava instável. Tente novamente hj e me dia como foi.

**Comment by ClarissaCapaverde** [comment]
Olá Perlin, tudo bem? Obrigada pelo teu retorno.

Segue dando o mesmo erro ao rodar o comando no R Studio Desktop. Quando rodo no RCloud o comando funciona. 

Meu computador é MAC e já fiz a instalação do Wget no Terminal. Acho que é alguma outra configuração que tenha que fazer no meu computador. 

Estou mandando os prints das tela do erro e do terminal. 

Se tiveres alguma sugestão de como posso resolver o problema.

Att, Clarissa

**Comment by msperlin** [comment]
Oi Clarissa, 

O seu issue é com o get_fre_data, certo? Favor abrir um issue no repositório do pacote GetFREData (esse é do defunto GetDFPData)
