### ISSUE TITLE
'wget' call had nonzero exit status - problems to download data

### ISSUE THREAD

**Issue by ronanalexand** [msperlin/GetDFPData#29]
Hi, i'am getting this error when trying to download the data

library(GetDFPData)
library(dplyr)

# set options
name.companies <- "AZUL S.A."
first.date <- '2015-12-31'
last.date  <- '2017-12-31'

# download data
df.reports <- gdfpd.GetDFPData(name.companies = name.companies,
                               first.date = first.date,
                               last.date = last.date)

Found cache file. Loading data..

Downloading data for 1 companies
First Date: 2015-12-31
Laste Date: 2017-12-31
Inflation index: dollar

Downloading inflation data
	Found cache file. Loading data..	Done

Inputs looking good! Starting download of files:

AZUL S.A.
	Available periods: 2017-12-31	2016-12-31

Processing 24112 - AZUL S.A.
	Finding info from Bovespa
		Found BOV cache file
	Processing 24112 - AZUL S.A. | date 2017-12-31
		Acessing DFP data | downloading filesh: wget: command not found
Error in utils::download.file(url = dl.link, destfile = dest.file, method = "wget",  : 
  'wget' call had nonzero exit status
Além disso: Warning message:
In system(paste("wget", paste(extra, collapse = " "), shQuote(url),  :
  erro ao executar comando
Error in if (file.size(dest.file) < 10) { : 
  valor ausente onde TRUE/FALSE necessário

**Comment by ronanalexand** [comment]
I'll close this for a time. I haven't understand that i need to install wget.

**Comment by msperlin** [comment]
Thanks.
