### ISSUE TITLE
Missing Stockholders ($history.stockholders)

### ISSUE THREAD

**Issue by raimundomarciano** [msperlin/GetDFPData#3]
$history.stockholders seems to miss many "Total" rows.

e.g., while running 

stock_azevedo = do.call(args = azevedo$history.stockholders, what=rbind)

for AZEVEDO & TRAVASSOS SA (both if data is imported from the rds file generated in the shiny app or directly imported in R with the corresponding function), data for 2013 does not show up, though there is data available for other info sets, like $fr.income.consolidated. Also, I couldn't find some stockholders in the list in some years, like Helber SA Part Administr, that shows up in the source file, but not in R.

I wasn't able to find a reason for that.

**Comment by msperlin** [comment]
Hi Raimundo,

Thanks for the issue report. It was a bug in the code and its fixed. 

Please use the new version in github. In a couple of days I'll update the data in the shinny app. 

Best,
