### ISSUE TITLE
Baixar informações usando o R

### ISSUE THREAD

**Issue by DanielWatanabe** [msperlin/GetDFPData#32]
Ola, tentei baixar utilizando o R com base no codigo fornecido e está dando este erro:

        Finding info from Bovespa | downloading and reading dataError in file(con, "r") : não é possível abrir a conexão
Além disso: Warning message:
In file(con, "r") : falha em InternetOpenUrl: 'The operation timed out'
> 
> gdfpd.export.DFP.data(df.reports = df.reports, type.export = type.export)
Error in gdfpd.export.DFP.data(df.reports = df.reports, type.export = type.export) : 
  objeto 'df.reports' não encontrado

**Comment by msperlin** [comment]
Oi Daniel,

É um problema com o servidor da B3. Vou investigar mais a fundo assim que puder e dou um retorno aqui. 

Pode ter sido uma instabilidade. Tente novamente o código e me diga como foi.

**Comment by DanielWatanabe** [comment]
Oi Marcelo, td bem?
acabei nao tentando novamente, pois farei isso em breve.
Estou dando continuidade nos meus levantamentos e percebi que uma informação constante no formulario de referencias não aparece na base do GETDFPdata. A informação refere-se a data de nascimento do membro do Board/Administração.
Vc sabe dizer se há alguma forma automática de baixarmos estes dados? veja abaixo a tela. Penso que é a mesma fonte onde o GETDFPdata extrai os dados do board..
abs



    Em sexta-feira, 6 de março de 2020 10:11:18 BRT, Marcelo S. Perlin <notifications@github.com> escreveu:  
 
 
Oi Daniel,

É um problema com o servidor da B3. Vou investigar mais a fundo assim que puder e dou um retorno aqui.

Pode ter sido uma instabilidade. Tente novamente o código e me diga como foi.

**Comment by DanielWatanabe** [comment]
OI Marcelo, td bem?
acredito que o Sr. não teve a oportunidade de ver meu email abaixo. Seria possível retorná-lo?
abs
    Em segunda-feira, 29 de junho de 2020 12:10:49 BRT, Daniel Watanabe <danielwatanabe@yahoo.com.br> escreveu:  
 
  Oi Marcelo, td bem?
acabei nao tentando novamente, pois farei isso em breve.
Estou dando continuidade nos meus levantamentos e percebi que uma informação constante no formulario de referencias não aparece na base do GETDFPdata. A informação refere-se a data de nascimento do membro do Board/Administração.
Vc sabe dizer se há alguma forma automática de baixarmos estes dados? veja abaixo a tela. Penso que é a mesma fonte onde o GETDFPdata extrai os dados do board..
abs



    Em sexta-feira, 6 de março de 2020 10:11:18 BRT, Marcelo S. Perlin <notifications@github.com> escreveu:  
 
 
Oi Daniel,

É um problema com o servidor da B3. Vou investigar mais a fundo assim que puder e dou um retorno aqui.

Pode ter sido uma instabilidade. Tente novamente o código e me diga como foi.

**Comment by msperlin** [comment]
Oi Daniel,

O dob (date of birth) está lá no FRE e é importado pelo GetDFPData. Mas,  muitas empresas ou não dão a informação, ou então, dão no formato errado.  O código busca importar o dob mas, qdo não consegue transformar para data, torna em NA.

Abc.

**Comment by msperlin** [comment]
Aproveitando, dá uma olhada no GetFREData, o qual será a nova iteração do pacote para dados do FRE. Veja aqui mais detalhes: https://www.msperlin.com/blog/post/2020-07-18-new_packages-getfredata-getdfpdata2/

**Comment by DanielWatanabe** [comment]
Otimo!! vou ver isso e te falo.
obrigado


Enviado do Yahoo Mail para iPhone


Em segunda-feira, julho 27, 2020, 4:29 PM, Marcelo S. Perlin <notifications@github.com> escreveu:




Aproveitando, dá uma olhada no GetFREData, o qual será a nova iteração do pacote para dados do FRE. Veja aqui mais detalhes: https://www.msperlin.com/blog/post/2020-07-18-new_packages-getfredata-getdfpdata2/
