### ISSUE TITLE
No DFP files available

### ISSUE THREAD

**Issue by Rui84** [msperlin/GetDFPData#33]
I have tried to download the data for couple of companies (using R and the shiny version) and could download the FRE / FCA files but it came "no DFP file available". One example was "ITAÚ UNIBANCO HOLDING S.A.". I am very new to using this but it seemed to be an issue with B3 site?

**Comment by msperlin** [comment]
Tks. I'll have a look as soon as I can.

**Comment by meumesmo** [comment]
I'm experiencing the same issue.

**Comment by msperlin** [comment]
CVM did not update its https certificate, resulting in an error in the download. I just fixed it for Linux using unsecure download options. The new version is in github.

As for Windows, I'll need to test it further. I'll post it here soon.

**Comment by msperlin** [comment]
Just tried in Windows and it is working fine. This issue was only found in Linux. 

Update the package (devtools::install_github('msperlin/GetDFPData')) and let me know if it is working.
