### ISSUE TITLE
Can't use "Fetch New Files"

### ISSUE THREAD

**Issue by carloshhelt** [msperlin/GetDFPData#35]
Good morning, msperlin! How are you ?

Well, I'm trying to use the amazing GetDFPData package to get some companies data for my paper and I need to use the most recent files in B3 database, therefore, I'm using the "fetch.new.files" argument.

However, I got stuck at this error: 

> Error in data.frame(id.company = my.id, id.file, version.file, dl.link,  : 
  arguments imply differing number of rows: 1, 7, 0

I'm trying to run the code below

```
first.date = '2018-01-01'
last.date = '2018-12-31'
r = NULL
attempt = 1
while( is.null(r) && attempt <= 20 ) {
    attempt = attempt + 1
    try(gdfpd.GetDFPData(name.companies = df.info$name.company, 
           first.date = first.date,last.date = last.date, 
           cache.folder = cache.folder, fetch.new.files = TRUE))}
```

I'm using the GetDFPData 1.5.3 v and I would appreciate your help.

**Comment by msperlin** [comment]
Good. 

Since a previous update the fetch.new.files is not working due to changes in B3 website. It sucks and nothing I can do to change it. In fact, the whole package will be replaced soon by a better source of data (CVM).

Best,
