### ISSUE TITLE
erro em inner_join_impl()

### ISSUE THREAD

**Issue by afortes51** [msperlin/GetDFPData#4]
Estou encontrando erro no inner_join abaixo: 

> name.companies <- "AMBEV S.A."
> first.date <-  "2015-12-31"
> last.date <- "2017-12-31"
> df.reports <- gdfpd.GetDFPData(name.companies = 'AMBEV S.A.', first.date = first.date, last.date = last.date)

Found cache file. Loading data..
Fetching new files from Bovespa.Joining, by = c("id.company", "listing.segment", "main.sector", "sub.sector", "segment", "tickers")
Error in inner_join_impl(x, y, by_x, by_y, aux_x, aux_y, na_matches) : 
  Can't join on 'listing.segment' x 'listing.segment' because of incompatible types (character / logical)
In addition: Warning message:
In readLines(my.link, encoding = "Latin1") :
  incomplete final line found on 'http://bvmf.bmfbovespa.com.br/pt-br/mercados/acoes/empresas/ExecutaAcaoConsultaInfoEmp.asp?CodCVM=23264&ViewDoc=0#a'

**Comment by msperlin** [comment]
Oi FOrtes, 

Este é um bug com uma opção nova para pegar arquivos mais recentes. PAra solucionar, basta usar opção fetch.new.files = FALSE. Irei arrumar isso hoje no CRAN. 
Veja abaixo o código:

name.companies <- "AMBEV S.A."
first.date <- "2015-12-31"
last.date <- "2017-12-31"
df.reports <- gdfpd.GetDFPData(name.companies = 'AMBEV S.A.', 
                               first.date = first.date, last.date = last.date, fetch.new.files = F)
