### ISSUE TITLE
The package is not capturing the incomes data.

### ISSUE THREAD

**Issue by gustfm** [msperlin/GetDFPData#6]
I tried make the capture of incomes data with the GetDFPData, but it came with your values zeroed.

**Comment by msperlin** [comment]
Please post your code so that I can look into it..

**Comment by gustfm** [comment]
```
library(GetDFPData)

dl.status <- gdfpd.download.file('http://www.rad.cvm.gov.br/enetconsulta/frmDownloadDocumento.aspx?CodigoInstituicao=2&NumeroSequencialDocumento=71563', 'C:/Users/gustavo/Documents/workspace/R/Teste/tempfile.zip', 1)
my.l <- gdfpd.read.dfp.zip.file('C:/Users/gustavo/Documents/workspace/R/Teste/tempfile.zip', folder.to.unzip = tempdir(), id.type = 'after 2011')

View(my.l)
```
When I show the my.l$df.incomes, the incomes values data are zeroed.

**Comment by msperlin** [comment]
You should not, in a normal situation, be calling gdfpd.download.file directly. I'm not sure why you are not using GetDFPData. 

Can you post the code using GetDFPData so that I can see the company and year?

**Comment by gustfm** [comment]
I used this code for to get information about the company:

`m.companies <- gdfpd.get.info.companies(type = "companies_files", cache.folder = "DFP Cache FOlder"`

And then I get the `dl.link` and I used in gdfpd.download.file. What did I do wrong?

**Comment by msperlin** [comment]
Nothing. But I cant debug your code without knowing the company and year or how you used the main function. Have a look at the function GetDFPData::GetDFPData.

**Comment by gustfm** [comment]
The company is **BANCO DO BRASIL S.A.**, the id.company is **1023** and the year is **2017-12-31**.

**Comment by gustfm** [comment]
I used the gdfpd.GetDFPData but the incomes and the assets are still came zeroed.

This was the code I used:
```
df.statements <- gdfpd.GetDFPData(name.companies = "BANCO DO BRASIL S.A.", first.date = "2017-12-31", folder.out = tempdir(), do.cache = TRUE, cache.folder = "DFP Cache Folder")
View(df.statements$fr.income[[1]])
View(df.statements$fr.assets[[1]])
```

**Comment by msperlin** [comment]
I was able to replicate the problem, but I couldn't see right away why it is happening. I'll have a deeper look soon. This issue will stay open until I fix it.

**Comment by gustfm** [comment]
It's ok, thank you so much.

**Comment by msperlin** [comment]
Hi gsoares, 

I figured out the bug and fixed it. You should reinstall the package using devtools:install_github(). 

Best,
