### ISSUE TITLE
Dados anteriores a 2010

### ISSUE THREAD

**Issue by AdrianoGF90** [msperlin/GetDFPData#9]
Bom dia!

Estou produzindo um artigo e preciso de dados anteriores a 2010, mas quando insiro a data (2003-01-01), só obtenho os relatórios que desejo a partir de 2010. Isso acontece porque não há, no banco de dados, informações anteriores a 2010 ou posso entender que a empresa não divulgou tais informações?

Desde já agradeço.

**Comment by msperlin** [comment]
Oi Adriano,

Qual versão estás usando, shiny (web) ou GetDFPData (R) ?

**Comment by AdrianoGF90** [comment]
O shiny. Tentei usar o R, mas não consegui encontrar o arquivo depois de copiar o script. 

Enviado do Yahoo Mail no Android 
 
  <div>Em Qua, 24 24e out 24e 2018 às 14:41, Marcelo S. Perlin</div><div><notifications@github.com> escreveu:</div>   
Oi Adriano,

Qual versão estás usando, shiny (web) ou GetDFPData (R) ?

**Comment by msperlin** [comment]
A versão shiny inicia os dados a partir de 2010, que é quando o sistema FRE foi implementado. Terás que usar a versão do R para ter acesso a dados anteriores a 2010.

Abc.
